### ISSUE TITLE
How to interpret the two output values of the offgaze_score and eye_orientation?

### ISSUE THREAD

**Issue by sweezin** [worldcoin/open-iris#15]
# {{How to interpret the two output values of the offgaze_score and eye_orientation}}

## Context

Please provide any relevant information about your setup. This is important in case the issue is not reproducible except for under certain conditions.

* Firmware Version:
* Operating System: windows
* SDK version:  V1.0.0
* Toolchain version:

## Expected Behavior

Please describe the behavior you are expecting

## Current Behavior

What is the current behavior?

## Failure Information (for bugs)

Please help provide information about the failure if this is a bug. If it is not a bug, please remove the rest of this template.

### Steps to Reproduce

Please provide detailed steps for reproducing the issue.

1. step 1
2. step 2
3. you get it...

### Failure Logs

Please include any relevant log snippets or files here.

**Comment by wiktorlazarski** [comment]
Closing since it duplicates this issue https://github.com/worldcoin/open-iris/issues/16
