### ISSUE TITLE
There is a tiny error at output_builders.py : 70

### ISSUE THREAD

**Issue by EliteWeapon** [worldcoin/open-iris#38]
# {{A tiny error in output_builders}}

error location: src/iris/orchestration/output_builders.py : 70

## Context

* Firmware Version:
* Operating System:
* SDK version:  v1.1.0
* Toolchain version:

## Expected Behavior

    geometry_mask, noise_mask = (
        call_trace["segmentation_binarization"] if call_trace["segmentation_binarization"] is **not** None else (None, None)
    )

## Current Behavior

    geometry_mask, noise_mask = (
        call_trace["segmentation_binarization"] if call_trace["segmentation_binarization"] is None else (None, None)
    )

**Comment by TanguyJeanneau** [comment]
Hi @EliteWeapon !

Thanks for noticing and raising this issue ! 
Yes you're right, there's indeed a typo here. This was noticed a few weeks ago and is fixed on [dev](https://github.com/worldcoin/open-iris/blob/56e905d66efa9051f112b3bad3576f021950d845/src/iris/orchestration/output_builders.py#L69), but the change isn't applied on `main` yet. We're releasing `open-iris@v1.1.1` this week, you should have a fixed version by Friday EoD

How is your experience using open-iris so far, anything you'd like to see improved ? 🙂 open-iris has been open-sourced recently, so we're eager to get feedback on how we can make user's life better and our software more useful !

**Comment by EliteWeapon** [comment]
Thank you much for your efforts and dedication. Due to open source, the application of iris recognition will become increasingly widespread.
