### ISSUE TITLE
model loading error in tensorrt_multilabel_segmentation

### ISSUE THREAD

**Issue by wangbofei11** [worldcoin/open-iris#47]
Thanks for great works

I cannot successfully load the model in tensorrt_multilabel_segmentation， can you  help? 
environment : open-iris 1.1.1，windows11，python3.8.19, cuda12.4, tensorrt-10.4.0-cp38
The details are as follows：
  iris_pipeline = iris.IRISPipeline()
  File "D:\works\iris\open-iris\src\iris\pipelines\iris_pipeline.py", line 83, in __init__
    self.nodes = self.instanciate_nodes()
  File "D:\works\iris\open-iris\src\iris\pipelines\iris_pipeline.py", line 167, in instanciate_nodes
    nodes = {
  File "D:\works\iris\open-iris\src\iris\pipelines\iris_pipeline.py", line 168, in <dictcomp>
    node.name: self.instanciate_node(
  File "D:\works\iris\open-iris\src\iris\pipelines\iris_pipeline.py", line 222, in instanciate_node
    return self.instanciate_class(node_class, algorithm_params)
  File "D:\works\iris\open-iris\src\iris\pipelines\iris_pipeline.py", line 244, in instanciate_class
    return object_class(**kwargs)
  File "D:\works\iris\open-iris\src\iris\nodes\segmentation\tensorrt_multilabel_segmentation.py", line 93, in create_from_hugging_face
    return TensorRTMultilabelSegmentation(model_path, input_num_channels, callbacks)
  File "D:\works\iris\open-iris\src\iris\nodes\segmentation\tensorrt_multilabel_segmentation.py", line 108, in __init__
    engine = self._load_engine(model_path)
  File "D:\works\iris\open-iris\src\iris\nodes\segmentation\tensorrt_multilabel_segmentation.py", line 203, in _load_engine
    raise RuntimeError(f"Engine evaluates to None! File {path} seems to be broken!")
RuntimeError: Engine evaluates to None! File D:\works\iris\open-iris\src\iris\nodes\segmentation\assets\models--Worldcoin--iris-semantic-segmentation\snapshots\e6c8fbb8e2e7e024a58818530a6e3ae5c005f47a\iris_semseg_upp_scse_mobilenetv2.engine seems to be broken!

**Comment by wiktorlazarski** [comment]
Hey @wangbofei11,

Thank you for raising the issue and your interest in `open-iris`.

Can I ask you to provide more information about the environment within which you are trying to load the model. All I'm seeing from error logs, you provided, is that you are currently using Windows11 machine. I wonder if there is a specific reason why you want to load TensorRT version of the model and not ONNX one for this environment? Or maybe it's just [this conditional import](https://github.com/worldcoin/open-iris/blob/dev/src/iris/nodes/segmentation/__init__.py) that forces you do so. Let me know if that's the case, I can help you to configure [default `IRISPipeline` YAML file](https://github.com/worldcoin/open-iris/blob/dev/src/iris/pipelines/confs/pipeline.yaml) such that ONNX version of the model will be used.

For more context: we generated/compiled TensorRT model to be used on the Orb, therefore I don't expect it to work properly on Windows machine.

Best regards,
Wiktor

**Comment by wangbofei11** [comment]
hello @wiktorlazarski 
1 The environment is described in first floor：   open-iris 1.1.1，windows11，python3.8.19, cuda12.4, tensorrt-10.4.0-cp38，What else do you need?

2 The reason I use tensorrt is because there are a lot of pictures to process，so I need to speed up with GPU. Now I've changed some code to run the onnx model with onnxruntime-gpu. But it would be nice if the tensorrt model worked as well ：）

**Comment by wiktorlazarski** [comment]
Got it!

Thank you for the response. I'm happy that you managed to use ONNX with a GPU provider. 

For TensorRT model, as I said, this version aims to be used on the Orb and it's very unlikely that we will provide one working on every other machines. To still make `open-iris` working on every other machine, we add ONNX model. 

Nevertheless, if you still are eager to use TensorRT version, one thing you can try to do is to convert ONNX model into TensorRT by yourself. Here is a resource that can give you guidance how to do that - https://docs.nvidia.com/deeplearning/tensorrt/quick-start-guide/index.html.

Let me know if that helps and I can close this issue.

Best regards,
Wiktor

**Comment by wangbofei11** [comment]
ok, i got it, thanks for your suggestion @wiktorlazarski

**Comment by wiktorlazarski** [comment]
I'm glad I could help. I'll close this issue. Feel free to reopen it if there is still something you'd like to discuss.
